name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 3 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not had any activity for 45 days and will be closed in 45 days if there continues to be no activity.'
        stale-issue-label: 'no-issue-activity'
        days-before-stale: 45
        days-before-close: 45
